### ISSUE TITLE
[soma_llsd_msgs] Full RGB-D image + mask?

### ISSUE THREAD

**Issue by nilsbore** [jayyoung/soma_llsd#2]
For the object search observation of the meta rooms we need full RGB + depth images + masks (this might be optional as we can do the reasoning here from the additional object). But importantly, we generally need more than just the masked images. As it would not be much more expensive, can we change the message to be rgb image + depth image + 8 bit mask image? @jayyoung

**Comment by jayyoung** [comment]
So, if I understand, extend the observation message: 

https://github.com/jayyoung/soma_llsd/blob/master/soma_llsd_msgs/msg/Observation.msg

To also include the _full_ (640x480, non-cropped/masked) depth image, rgb image and mask? You can get the first two of these out by additionally using the Scene store, so that each Segment uses its scene_id field to link to a Scene message: 

https://github.com/jayyoung/soma_llsd/blob/master/soma_llsd_msgs/msg/Scene.msg

Which will store the full rgb/depth/rgbd. It's set up this way because in our system we might expect there to be multiple segments from a single observation, but I know that's different for you!

Or am I not following? But you're right that the full mask should be added to the Observation, so I'll get on adding that. The system as it is just contains the stuff we need to use here, so just let me know what extensions are needed.

**Comment by nilsbore** [comment]
I think you're following. But as I understand it, you have one `Scene` for one or multiple `Segment`s. We assume that one object learn observation from you would just be one `Segment`, i.e. multiple `Observation`s. Therefore we want full RGBD+mask for every `Observation`, as opposed to for the `Segment`s.

**Comment by jayyoung** [comment]
Hey sorry for the lead time on this, there's been a lot of robot hacking to do!

I see what you mean now and I realise I've made a big mistake with the structure of the messages. So to fix this I've moved the scene_id field to the Observation message, so the masks in there can now directly refer to the images in a Scene message, which I think solves the problem. The Segment objects now also keep themselves updated with a list of the scenes in which they appear, which may be useful down the line.

The Scene contains the root rgb, depth etc. data, and then the Observation contains any masks derived from that data, and the Segment links all of these together across multiple Scenes.

Just pushed these changes.

**Comment by nilsbore** [comment]
But why keep the images in Scene rather than in Observation since Observation already has all the other images?

**Comment by nilsbore** [comment]
Ok, I see the logic now I think. Scene is just a pure sensor observation and then Observation allows different frameworks to do different forms of reasoning to segment and extract objects.

**Comment by jayyoung** [comment]
Yep, that's the idea! It may be the case, for example, that any number of frameworks might have their own set of Segments/Observations, all ultimately being derived from the same instance of robot sensor data. So keeping that common is a good idea, but the rest of it can be application specific in origin.

**Comment by jayyoung** [comment]
So @nilsbore if you think the structure of these messages is OK, I will merge this into the main SOMA package, and it'll be released when we merge and release the update branch. I'm sure there might be a few things here and there we might want to update though, but we can do that as need arises.

**Comment by nilsbore** [comment]
Fixed!
